name 'my_example_app'
license 'All rights reserved'
version '0.1.0'

depends 'apt'
depends 'curl'
depends 'vim'
depends 'git'
depends 'apache2'
depends 'php'
depends 'mysql'
depends 'mysql2_chef_gem'
depends 'database'
depends 'composer'
