Vagrant.configure('2') do |config|
  config.vm.box = 'opscode-ubuntu-14.04'
  config.vm.box_url = 'http://opscode-vm-bento.s3.amazonaws.com/'\
                      'vagrant/virtualbox/'\
                      'opscode_ubuntu-14.04_chef-provisionerless.box'
  config.omnibus.chef_version = '11.16.0'

  config.vm.provider 'virtualbox' do |box|
    box.memory = 1024
    box.cpus = 1
  end

  config.vm.provision 'chef_zero' do |chef|
    chef.add_recipe 'my_example_app'
    chef.log_level          = :debug
    chef.cookbooks_path     = 'cookbooks/'
    chef.environment        = 'development'
    chef.environments_path  = 'environments/'
    chef.custom_config_path = 'Vagrantfile.chef'
  end

  sync_dir = "/var/www/my_example_app"
  mount_options = ['dmode=777,fmode=777']
  config.vm.synced_folder '../', sync_dir, mount_options: mount_options
  config.vm.network :private_network, ip: '11.11.11.11'
end
